---
- name: Create MySQL Exporter system user
  user:
    name: mysqld_exporter
    system: yes
    shell: /bin/false
    create_home: no

- name: Install PyMySQL for Python 3
  apt:
    name: python3-pymysql
    state: present

- name: Ensure MySQLdb module is installed for Python 3
  apt:
    name: python3-mysqldb
    state: present

- name: Create user 'mysqld_exporter'
  community.mysql.mysql_query:
    login_user: root
    login_password: ""  # Since your root user has no password
    query: "CREATE USER IF NOT EXISTS 'mysqld_exporter'@'localhost' IDENTIFIED BY 'password' WITH MAX_USER_CONNECTIONS 3;"
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Grant PROCESS, REPLICATION CLIENT, SELECT privileges to 'mysqld_exporter'
  community.mysql.mysql_query:
    login_user: root
    login_password: ""  # Assuming your root user has no password
    query: "GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'mysqld_exporter'@'localhost';"
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Download MySQL Exporter tarball
  get_url:
    url: https://github.com/prometheus/mysqld_exporter/releases/download/v0.15.1/mysqld_exporter-0.15.1.linux-amd64.tar.gz
    dest: /tmp/mysqld_exporter-0.15.1.linux-amd64.tar.gz

- name: Extract MySQL Exporter tarball
  unarchive:
    src: /tmp/mysqld_exporter-0.15.1.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Move MySQL Exporter binary
  copy:
    src: /tmp/mysqld_exporter-0.15.1.linux-amd64/mysqld_exporter
    dest: /usr/local/bin/mysqld_exporter
    remote_src: yes
    mode: 0755

- name: Copy Mysqld systemd service file
  copy:
    src: files/mysqld_exporter.service
    dest: /etc/systemd/system/mysqld_exporter.service
    mode: 0644

- name: Copy .mysqld_exporter.cnf file to /etc/      
  copy:
    dest: /etc/.mysqld_exporter.cnf
    content: |
      [client]
      user=mysqld_exporter
      password=password

- name: Clean up MySQL Exporter tarball and extracted files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/mysqld_exporter-0.15.1.linux-amd64/
    - /tmp/mysqld_exporter-0.15.1.linux-amd64.tar.gz

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable Mysqld Exporter service
  systemd:
    name: mysqld_exporter
    enabled: yes

- name: Start Mysqld Exporter service
  systemd:
    name: mysqld_exporter
    state: started

- name: Restart Mysqld Exporter service
  systemd:
    name: mysqld_exporter
    state: restarted
    