---
---
- name: Install PyMySQL for Python 3
  apt:
    name: python3-pymysql
    state: present

- name: Ensure MySQLdb module is installed for Python 3
  apt:
    name: python3-mysqldb
    state: present

# - name: Check if 'monitor' user exists
#   community.mysql.mysql_query:
#     login_user: root
#     login_password: ""  # Assuming your root user has no password
#     query: "SELECT COUNT(*) FROM mysql.user WHERE user = 'monitor';"
#     login_unix_socket: /run/mysqld/mysqld.sock
#   register: monitor_user_exists

- name: Create user 'monitor' if not exists
  community.mysql.mysql_query:
    login_user: root
    login_password: ""  # Assuming your root user has no password
    query: "CREATE USER IF NOT EXISTS 'monitor'@'%' IDENTIFIED BY 'monitor';"
    login_unix_socket: /run/mysqld/mysqld.sock
  # when: monitor_user_exists.query_result[0][0] == 0

- name: Grant USAGE and REPLICATION CLIENT privileges to 'monitor'
  community.mysql.mysql_query:
    login_user: root
    login_password: ""  # Assuming your root user has no password
    query: "GRANT USAGE, REPLICATION CLIENT ON *.* TO 'monitor'@'%';"
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Flush privileges on MySQL server
  community.mysql.mysql_query:
    login_user: root
    login_password: ""  # Assuming your root user has no password
    query: "FLUSH PRIVILEGES;"
    login_unix_socket: /run/mysqld/mysqld.sock

- name: Configuring ProxySQL to use the monitor user
  shell: |
    mysql -u admin -padmin -h 127.0.0.1 -P6032 --prompt 'ProxySQLAdmin> ' << EOF
    UPDATE global_variables SET variable_value='monitor' WHERE variable_name='mysql-monitor_username';
    UPDATE global_variables SET variable_value='monitor' WHERE variable_name='mysql-monitor_password';
    UPDATE global_variables SET variable_value='2000' WHERE variable_name IN ('mysql-monitor_connect_interval','mysql-monitor_ping_interval','mysql-monitor_read_only_interval');
    LOAD MYSQL VARIABLES TO RUNTIME;
    SAVE MYSQL VARIABLES TO DISK;
    EOF
