---
- name: Configuring monitoring on MySQL server
  mysql_user:
    name: monitor
    password: monitor
    priv: '*.*:USAGE,REPLICATION CLIENT'
    host: '%'
    state: present

- name: Flush privileges on MySQL server
  mysql_db:
    name: '*'
    state: flush_privileges

- name: Configuring ProxySQL to use the monitor user
  shell: |
    mysql -u admin -padmin -h 127.0.0.1 -P6032 --prompt 'ProxySQLAdmin> ' << EOF
    UPDATE global_variables SET variable_value='monitor' WHERE variable_name='mysql-monitor_username';
    UPDATE global_variables SET variable_value='monitor' WHERE variable_name='mysql-monitor_password';
    UPDATE global_variables SET variable_value='2000' WHERE variable_name IN ('mysql-monitor_connect_interval','mysql-monitor_ping_interval','mysql-monitor_read_only_interval');
    LOAD MYSQL VARIABLES TO RUNTIME;
    SAVE MYSQL VARIABLES TO DISK;
    EOF
