tasks:
  - name: Update apt cache
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: Install Nginx
    apt:
      name: nginx
      state: present

  - name: Ensure Nginx is running
    service:
      name: nginx
      state: started
      enabled: yes

  - name: Add Ondrej PHP PPA
    apt_repository:
      repo: ppa:ondrej/php
      state: present

  - name: Update apt cache after adding PPA
    apt:
      update_cache: yes

  - name: Install PHP 7.4-FPM
    apt:
      name: php7.4-fpm
      state: present

  - name: Ensure PHP 7.4-FPM is running
    service:
      name: php7.4-fpm
      state: started
      enabled: yes

  - name: Copy Nginx default site configuration
    copy:
      src: files/default
      dest: /etc/nginx/sites-available/default
      mode: '0644'

  - name: Restart Nginx
    service:
      name: nginx
      state: restarted

  - name: Set permissions for /var/www/html
    file:
      path: /var/www/html
      mode: '0777'
      recurse: yes

  - name: Copy index.php to /var/www/html
    copy:
      src: files/index.php
      dest: /var/www/html/index.php
      mode: '0644'

